name: Update Profile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # STEP 1: Update Medium Blog Posts
      - name: Fetch Medium Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ajeets_91456"
          readme_path: "./README.md"
          max_post_count: 5
          tag_post_pre_newline: true

      # STEP 2: Update GitHub Activity
      - name: Update README with recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: singhajeet79
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 5
          # Note: If you want to see your commits, add PushEvent to this list
          FILTER_EVENTS: IssueCommentEvent,IssuesEvent,PullRequestEvent,ReleaseEvent,PushEvent
          TARGET_FILE: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
